services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    ports:
      - 11434:11434
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest

  # Add the service python-app which is the Python Flask app defined in app folder and the Dockerfile in the app directory
  python-app:
    build:
      context: ./app
    container_name: python-app
    ports:
      - 5000:5000
    pull_policy: always
    tty: true
    restart: unless-stopped
    depends_on:
      - python-app-db
    environment:
      - DATABASE_URL=postgresql://python_app:python_app@python-app-db:5432/python_app

  python-app-db:
    image: postgres:13
    container_name: python-app-db
    environment:
      POSTGRES_USER: python_app
      POSTGRES_PASSWORD: python_app
      POSTGRES_DB: python_app
    ports:
      - 5432:5432
    pull_policy: always
    tty: true
    restart: unless-stopped

volumes:
  ollama: 